// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sensorInflightValue struct {
	_       structs.HostLayout
	StartNs uint64
	Args    [6]uint64
	Pid     uint32
	Uid     uint32
	Nr      uint32
	_       [4]byte
}

type sensorWakeupValue struct {
	_         structs.HostLayout
	TsNs      uint64
	WakerPid  uint32
	WakerTid  uint32
	TargetCpu uint32
	WakerComm [16]int8
	_         [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	sensorMapConfig            = "config"
	sensorMapDrops             = "drops"
	sensorMapEvents            = "events"
	sensorMapIgnoredTgids      = "ignored_tgids"
	sensorMapInflight          = "inflight"
	sensorMapWakeups           = "wakeups"
	sensorMapWatchedSyscalls   = "watched_syscalls"
	sensorProgTraceSchedWakeup = "trace_sched_wakeup"
	sensorProgTraceSysEnter    = "trace_sys_enter"
	sensorProgTraceSysExit     = "trace_sys_exit"
)

// loadSensor returns the embedded CollectionSpec for sensor.
func loadSensor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SensorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load sensor: %w", err)
	}

	return spec, err
}

// loadSensorObjects loads sensor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sensorObjects
//	*sensorPrograms
//	*sensorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSensorObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadSensor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sensorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorSpecs struct {
	sensorProgramSpecs
	sensorMapSpecs
	sensorVariableSpecs
}

// sensorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorProgramSpecs struct {
	TraceSchedWakeup *ebpf.ProgramSpec `ebpf:"trace_sched_wakeup"`
	TraceSysEnter    *ebpf.ProgramSpec `ebpf:"trace_sys_enter"`
	TraceSysExit     *ebpf.ProgramSpec `ebpf:"trace_sys_exit"`
}

// sensorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorMapSpecs struct {
	Config          *ebpf.MapSpec `ebpf:"config"`
	Drops           *ebpf.MapSpec `ebpf:"drops"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	IgnoredTgids    *ebpf.MapSpec `ebpf:"ignored_tgids"`
	Inflight        *ebpf.MapSpec `ebpf:"inflight"`
	Wakeups         *ebpf.MapSpec `ebpf:"wakeups"`
	WatchedSyscalls *ebpf.MapSpec `ebpf:"watched_syscalls"`
}

// sensorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sensorVariableSpecs struct {
}

// sensorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorObjects struct {
	sensorPrograms
	sensorMaps
	sensorVariables
}

func (o *sensorObjects) Close() error {
	return _SensorClose(
		&o.sensorPrograms,
		&o.sensorMaps,
	)
}

// sensorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorMaps struct {
	Config          *ebpf.Map `ebpf:"config"`
	Drops           *ebpf.Map `ebpf:"drops"`
	Events          *ebpf.Map `ebpf:"events"`
	IgnoredTgids    *ebpf.Map `ebpf:"ignored_tgids"`
	Inflight        *ebpf.Map `ebpf:"inflight"`
	Wakeups         *ebpf.Map `ebpf:"wakeups"`
	WatchedSyscalls *ebpf.Map `ebpf:"watched_syscalls"`
}

func (m *sensorMaps) Close() error {
	return _SensorClose(
		m.Config,
		m.Drops,
		m.Events,
		m.IgnoredTgids,
		m.Inflight,
		m.Wakeups,
		m.WatchedSyscalls,
	)
}

// sensorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorVariables struct {
}

// sensorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSensorObjects or ebpf.CollectionSpec.LoadAndAssign.
type sensorPrograms struct {
	TraceSchedWakeup *ebpf.Program `ebpf:"trace_sched_wakeup"`
	TraceSysEnter    *ebpf.Program `ebpf:"trace_sys_enter"`
	TraceSysExit     *ebpf.Program `ebpf:"trace_sys_exit"`
}

func (p *sensorPrograms) Close() error {
	return _SensorClose(
		p.TraceSchedWakeup,
		p.TraceSysEnter,
		p.TraceSysExit,
	)
}

func _SensorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed sensor_bpfel.o
var _SensorBytes []byte
