"""REST API handlers facade."""

from kernel_ai.http.api_handlers.kernel import (
    get_execution_context,
    io_open_files,
    io_pulse,
    kernel_data,
    kernel_dna,
    ml_anomalies,
    ml_drift,
    nginx_files,
    process_kernel_map,
    sentry_test,
    syscalls_realtime,
)
from kernel_ai.http.api_handlers.network_system import (
    active_connections,
    devices_realtime,
    ext4_anatomy,
    ext4_journal,
    filesystem_blocks,
    hot_files,
    isolation_context,
    network_stack_realtime,
    path_walk,
    traceroute_info,
)
from kernel_ai.http.api_handlers.processes import (
    get_ipc_links,
    get_proc_graph,
    get_proc_matrix,
    get_proc_timeline,
    get_proc_timeline_branches,
    get_process_cpu,
    get_process_fds,
    get_process_files,
    get_process_threads,
    get_processes,
    get_processes_detailed,
    processes_realtime,
    scheduler_pelt,
)
from kernel_ai.http.api_handlers.security_logs import (
    crypto_aes_demo,
    crypto_realtime,
    ingest_frontend_logs,
    security_realtime,
)

__all__ = [
    "active_connections",
    "crypto_aes_demo",
    "crypto_realtime",
    "devices_realtime",
    "ext4_anatomy",
    "ext4_journal",
    "filesystem_blocks",
    "hot_files",
    "path_walk",
    "get_execution_context",
    "get_ipc_links",
    "get_proc_graph",
    "get_proc_matrix",
    "get_proc_timeline",
    "get_proc_timeline_branches",
    "get_process_cpu",
    "get_process_fds",
    "get_process_files",
    "get_process_kernel_map",
    "get_process_threads",
    "get_processes",
    "get_processes_detailed",
    "ingest_frontend_logs",
    "io_open_files",
    "io_pulse",
    "isolation_context",
    "kernel_data",
    "kernel_dna",
    "ml_anomalies",
    "ml_drift",
    "network_stack_realtime",
    "nginx_files",
    "process_kernel_map",
    "processes_realtime",
    "scheduler_pelt",
    "security_realtime",
    "sentry_test",
    "syscalls_realtime",
    "traceroute_info",
]

